version: '3.8'

services:
  mysql:
    image: mysql:5.7
    container_name: mysql
    # restart: unless-stopped
    environment:
      MYSQL_DATABASE: ${KC_DB}
      MYSQL_USER: ${KC_USER}
      MYSQL_PASSWORD: ${KC_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${KC_PASSWORD}
    ports:
      - 3306:3306
    # volumes:
    #   - mysql_keycloak:/var/lib/mysql

  keycloak:
    image: quay.io/keycloak/keycloak:${KC_VERSION}
    depends_on:
      - mysql
    container_name: keycloak
    # restart: unless-stopped
    environment:
      KC_DB: mysql
      KC_DB_URL: 'jdbc:mysql://mysql_keycloak:3306/keycloak'
      KC_DB_USERNAME: ${KC_USER}
      KC_DB_PASSWORD: ${KC_PASSWORD}
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: ${KC_ADMIN_PASSWORD}
      # KC_METRICS_ENABLED: true
      # KC_HEALTH_ENABLED: true
    ports:
      - 8080:8080
    command: start-dev
    healthcheck:
      test: 'curl -f http://localhost:8080/admin || exit 1'
